// export async function onRequestPost({ request, env }) {
//   const formData = await request.formData();
//   const recaptchaToken = formData.get('g-recaptcha-response');
//   const recaptchaVerifyUrl = `https://www.google.com/recaptcha/api/siteverify?secret=${env.RECAPTCHA_SECRET}&response=${recaptchaToken}`;
  
//   // Set your acceptable threshold for v3 (0.0 to 1.0)
//   const MIN_SCORE = 0.5; 

//   try {
//     // 1. Verify reCAPTCHA token with Google
//     const recaptchaResponse = await fetch(recaptchaVerifyUrl, { method: 'POST' });
//     const recaptchaData = await recaptchaResponse.json();

//     // 💡 CRITICAL DEBUG STEP: Log the Google response to Cloudflare logs
//     console.log('reCAPTCHA Data:', JSON.stringify(recaptchaData));

//     // 2. Check for overall success AND score threshold
//     if (!recaptchaData.success || recaptchaData.score < MIN_SCORE) {
//       console.error('Recaptcha failed check. Score:', recaptchaData.score, 'Errors:', recaptchaData['error-codes']);
//       return new Response(
//           `reCAPTCHA verification failed. Score: ${recaptchaData.score}`, 
//           { status: 403 }
//       );
//     }
    
//     // 3. FORWARD DATA TO GOOGLE SHEET
//     const sheetResponse = await fetch(env.SCRIPT_URL, {
//       method: 'POST',
//       body: formData,
//     });

//     if (sheetResponse.ok) {
//       return new Response('Callback requested successfully!', { status: 200 });
//     } else {
//       // Log the non-200 response details from Google Apps Script
//       console.error('Google Sheet Apps Script failed with status:', sheetResponse.status);
//       return new Response('Form submission failed on the backend.', { status: 500 });
//     }

//   } catch (error) {
//     console.error('Uncaught error during form processing:', error.message);
//     return new Response('An internal error occurred.', { status: 500 });
//   }
// }

export async function onRequestPost({ request, env }) {
  const formData = await request.formData();
  
  // Get the token generated by Turnstile
  const turnstileToken = formData.get('cf-turnstile-response');

  // Verify the token using the Turnstile endpoint
  const verificationUrl = 'https://challenges.cloudflare.com/turnstile/v0/siteverify';

  const verificationResponse = await fetch(verificationUrl, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      secret: env.TURNSTILE_SECRET, // Your Secret Key
      response: turnstileToken,
      // Optional: Pass the user's IP for better security (Cloudflare provides this header)
      remoteip: request.headers.get('CF-Connecting-IP'), 
    }),
  });
  

  const verificationData = await verificationResponse.json();

  if (!verificationData.success) {
    // 💡 DEBUGGING RETURN: Get the error codes array and format it
    const errorCodes = verificationData['error-codes'] ? verificationData['error-codes'].join(', ') : 'Unknown Error';
    
    console.error("Turnstile failed:", verificationData['error-codes']);
    
    // Return the specific error codes to the user
    return new Response(
      `Bot verification failed. Error Code(s): ${errorCodes}.`, 
      { status: 403 }
    );
  }



  // --- FORWARD DATA TO GOOGLE SHEET ---
  const sheetResponse = await fetch(env.SCRIPT_URL, {
    method: 'POST',
    body: formData,
  });

  if (sheetResponse.ok) {
    return new Response('Callback requested successfully!', { status: 200 });
  } else {
    // Return the actual HTTP status if the Google Sheet call fails
    return new Response(`Form submission failed on the backend. Sheet Status: ${sheetResponse.status}`, { status: 500 });
  }
}